baseURL = "https://rkanet.github.io/cookbook"
publishdir = "docs"
languageCode = "en-us"
title = "Kitchen"
theme = "StronglyTyped"

# sectionPagesMenu = "main"

canonifyurls = true

preserveTaxonomyNames = true
[taxonomies]
	priprava = "priprava"
	igredience = "ingredience"
	kategorie = "kategorie"
	tag = "tags"
	taxomony = "taxomonies"

[[menu.main]]
name = "Home"
url = "/"
weight = 1
[menu.main.params]
icon = "solid fa-home"

[[menu.main]]
name = "Recepty"
url = "/recepty/"
weight = 2
[menu.main.params]
icon = "solid fa-book"

[[menu.main]]
name = "Galerie"
url = "/galerie/"
weight = 3
[menu.main.params]
icon = "solid fa-images"

[[menu.main]]
name = "How-to"
url = "/how-to/"
weight = 4
[menu.main.params]
icon = "solid fa-lightbulb"

	